import { useEffect, useState } from 'react';
import { NavLink } from 'react-router-dom';
import { Activity, AlertTriangle, BookOpen, Bot, Plus, RefreshCw, Sparkles, TrendingUp, Users } from 'lucide-react';
import { adminGetStats, adminAIInsights } from '../../services/api-backend';

const CATEGORY_COLORS = [
  '#6366f1','#a855f7','#0ea5e9','#10b981','#f59e0b',
  '#ef4444','#ec4899','#14b8a6','#f97316','#84cc16',
];

function StatCard({ icon: Icon, value, label, gradient, iconBg, iconColor, change }) {
  return (
    <div className="admin-stat-card" style={{ '--card-gradient': gradient }}>
      <div className="admin-stat-icon" style={{ '--icon-bg': iconBg, '--icon-color': iconColor }}>
        <Icon size={20} />
      </div>
      <div className="admin-stat-value">{value}</div>
      <div className="admin-stat-label">{label}</div>
      {change !== undefined && (
        <div className={`admin-stat-change ${change < 0 ? 'down' : ''}`}>
          {change >= 0 ? '↑' : '↓'} {Math.abs(change)} this month
        </div>
      )}
    </div>
  );
}

export default function AdminDashboard() {
  const [stats, setStats] = useState(null);
  const [categoryStats, setCategoryStats] = useState([]);
  const [monthlyBorrows, setMonthlyBorrows] = useState([]);
  const [topBooks, setTopBooks] = useState([]);
  const [aiInsights, setAiInsights] = useState(null);
  const [aiLoading, setAiLoading] = useState(false);
  const [loading, setLoading] = useState(true);

  async function loadStats() {
    setLoading(true);
    const res = await adminGetStats();
    if (res.success) {
      setStats(res.stats);
      setCategoryStats(res.categoryStats || []);
      setMonthlyBorrows(res.monthlyBorrows || []);
      setTopBooks(res.topBooks || []);
    }
    setLoading(false);
  }

  async function loadInsights() {
    setAiLoading(true);
    const res = await adminAIInsights();
    if (res.success) setAiInsights(res);
    setAiLoading(false);
  }

  useEffect(() => {
    loadStats();
    loadInsights();
  }, []);

  const maxBorrow = Math.max(...monthlyBorrows.map((m) => m.count), 1);

  if (loading) {
    return (
      <div className="admin-loading">
        <div className="admin-spinner" />
      </div>
    );
  }

  return (
    <div>
      {/* AI Insights Panel */}
      <div className="admin-ai-panel">
        <div className="admin-ai-header">
          <div className="admin-ai-icon">
            <Sparkles size={18} color="white" />
          </div>
          <div>
            <div className="admin-ai-title">AI Library Insights</div>
            <div className="admin-ai-subtitle">Powered by Gemini AI</div>
          </div>
          <button
            className="admin-btn admin-btn-secondary admin-btn-sm"
            style={{ marginLeft: 'auto' }}
            onClick={loadInsights}
            disabled={aiLoading}
          >
            <RefreshCw size={12} className={aiLoading ? 'spin' : ''} />
            {aiLoading ? 'Generating...' : 'Refresh'}
          </button>
        </div>
        <div className="admin-ai-text">
          {aiLoading ? (
            <div style={{ display: 'flex', gap: 6 }}>
              <div className="admin-skeleton" style={{ height: 14, width: '70%', borderRadius: 4 }} />
            </div>
          ) : aiInsights?.insights || 'Click Refresh to generate AI insights about your library.'}
        </div>
        {aiInsights?.aiGenerated && (
          <div className="admin-ai-generated">
            <Sparkles size={10} />
            Generated by Gemini AI
          </div>
        )}
      </div>

      {/* Stats Grid */}
      <div className="admin-stats-grid">
        <StatCard
          icon={BookOpen} value={stats?.totalBooks || 0} label="Total Books"
          gradient="linear-gradient(90deg, #6366f1, #a855f7)"
          iconBg="rgba(99,102,241,0.15)" iconColor="#818cf8"
        />
        <StatCard
          icon={Users} value={stats?.totalUsers || 0} label="Registered Students"
          gradient="linear-gradient(90deg, #0ea5e9, #6366f1)"
          iconBg="rgba(14,165,233,0.15)" iconColor="#38bdf8"
        />
        <StatCard
          icon={Activity} value={stats?.activeBorrows || 0} label="Active Borrows"
          gradient="linear-gradient(90deg, #10b981, #0ea5e9)"
          iconBg="rgba(16,185,129,0.15)" iconColor="#34d399"
        />
        <StatCard
          icon={AlertTriangle} value={stats?.overdue || 0} label="Overdue Books"
          gradient="linear-gradient(90deg, #ef4444, #f59e0b)"
          iconBg="rgba(239,68,68,0.15)" iconColor="#f87171"
        />
      </div>

      {/* Quick Actions */}
      <div className="admin-quick-actions">
        <NavLink to="/admin/books" className="admin-quick-action">
          <div className="admin-quick-action-icon" style={{ background: 'rgba(99,102,241,0.15)' }}>
            <BookOpen size={20} color="#818cf8" />
          </div>
          <span className="admin-quick-action-label">Manage Books</span>
        </NavLink>
        <NavLink to="/admin/users" className="admin-quick-action">
          <div className="admin-quick-action-icon" style={{ background: 'rgba(14,165,233,0.15)' }}>
            <Users size={20} color="#38bdf8" />
          </div>
          <span className="admin-quick-action-label">Manage Users</span>
        </NavLink>
        <NavLink to="/admin/borrows" className="admin-quick-action">
          <div className="admin-quick-action-icon" style={{ background: 'rgba(16,185,129,0.15)' }}>
            <Activity size={20} color="#34d399" />
          </div>
          <span className="admin-quick-action-label">Borrow Records</span>
        </NavLink>
        <NavLink to="/admin/ai" className="admin-quick-action">
          <div className="admin-quick-action-icon" style={{ background: 'rgba(168,85,247,0.15)' }}>
            <Bot size={20} color="#c084fc" />
          </div>
          <span className="admin-quick-action-label">AI Features</span>
        </NavLink>
      </div>

      {/* Charts */}
      <div className="admin-charts-grid">
        {/* Monthly Borrows Bar Chart */}
        <div className="admin-chart-card">
          <div className="admin-card-header">
            <div>
              <div className="admin-card-title">Monthly Borrow Activity</div>
              <div className="admin-card-subtitle">Last 6 months</div>
            </div>
            <TrendingUp size={16} color="var(--admin-primary-light)" />
          </div>
          {monthlyBorrows.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '40px', color: 'var(--admin-text-dim)', fontSize: 13 }}>
              No borrow activity yet
            </div>
          ) : (
            <div className="admin-bar-chart-area">
              {monthlyBorrows.map((m) => {
                const pct = (m.count / maxBorrow) * 100;
                const [year, month] = m.label.split('-');
                const label = new Date(Number(year), Number(month) - 1).toLocaleDateString('en', { month: 'short' });
                return (
                  <div key={m.label} className="admin-bar-wrapper">
                    <div className="admin-bar-value-label">{m.count}</div>
                    <div className="admin-bar" style={{ height: `${Math.max(pct, 4)}%` }} />
                    <div className="admin-bar-x-label">{label}</div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Category Distribution */}
        <div className="admin-chart-card">
          <div className="admin-card-header">
            <div>
              <div className="admin-card-title">Books by Category</div>
              <div className="admin-card-subtitle">{categoryStats.length} categories</div>
            </div>
          </div>
          <div className="admin-category-list">
            {categoryStats.slice(0, 8).map((c, i) => {
              const pct = (c.count / (stats?.totalBooks || 1)) * 100;
              return (
                <div key={c.category} className="admin-category-item">
                  <div className="admin-category-dot" style={{ background: CATEGORY_COLORS[i % CATEGORY_COLORS.length] }} />
                  <span className="admin-category-name">{c.category}</span>
                  <div className="admin-category-bar-wrap">
                    <div className="admin-category-bar-fill" style={{ width: `${pct}%`, background: CATEGORY_COLORS[i % CATEGORY_COLORS.length] }} />
                  </div>
                  <span className="admin-category-count">{c.count}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Bottom Row: Top Books + Summary */}
      <div className="admin-two-col">
        {/* Top Borrowed Books */}
        <div className="admin-chart-card">
          <div className="admin-card-header">
            <div className="admin-card-title">Top Borrowed Books</div>
          </div>
          <div className="admin-top-books">
            {topBooks.length === 0 ? (
              <div style={{ color: 'var(--admin-text-dim)', fontSize: 13, padding: '12px 0' }}>No borrow data yet.</div>
            ) : topBooks.map((b, i) => (
              <div key={i} className="admin-top-book-item">
                <div className="admin-top-book-rank">#{i + 1}</div>
                <div className="admin-top-book-info">
                  <div className="admin-top-book-title">{b.title}</div>
                  <div className="admin-top-book-author">{b.author}</div>
                </div>
                <div className="admin-top-book-count">{b.count}×</div>
              </div>
            ))}
          </div>
        </div>

        {/* Library Summary */}
        <div className="admin-chart-card">
          <div className="admin-card-header">
            <div className="admin-card-title">Library Summary</div>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            {[
              { label: 'Total Books', value: stats?.totalBooks || 0, color: '#818cf8' },
              { label: 'Total Borrows (all time)', value: stats?.totalBorrows || 0, color: '#38bdf8' },
              { label: 'Successfully Returned', value: stats?.returnedBorrows || 0, color: '#34d399' },
              { label: 'Currently Borrowed', value: stats?.activeBorrows || 0, color: '#f59e0b' },
              { label: 'Overdue', value: stats?.overdue || 0, color: '#f87171' },
            ].map((row) => (
              <div key={row.label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: 13, color: 'var(--admin-text-muted)' }}>{row.label}</span>
                <span style={{ fontSize: 15, fontWeight: 700, color: row.color }}>{row.value}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
